# Generated by Django 4.2.6 on 2023-10-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField()),
                ('hoten', models.CharField(max_length=255)),
                ('ngaysinh', models.CharField(max_length=255)),
                ('thangsinh', models.CharField(max_length=255)),
                ('namsinh', models.CharField(max_length=255)),
            ],
        ),
    ]
